# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qAn_cNL4NwBxJAnjbMP1_otwM7-uPss
"""

from datetime import date

# Определим класс для экзаменов
class Exam:
    def __init__(self, subject, exam_date, teacher, grade):
        self.subject = subject
        self.exam_date = exam_date
        self.teacher = teacher
        self.grade = grade

# Определим класс для студентов
class Student:
    def __init__(self, last_name, first_name, birth_date, exams):
        self.last_name = last_name
        self.first_name = first_name
        self.birth_date = birth_date
        self.exams = exams

    def average_grade(self):
        return sum(exam.grade for exam in self.exams) / len(self.exams)

# Создадим список студентов с их экзаменами
students = [
    Student("Иванов", "Иван", date(2000, 1, 15), [
        Exam("Математика", date(2022, 6, 10), "Петров П.П.", 5),
        Exam("Физика", date(2022, 6, 15), "Сидоров С.С.", 4),
        Exam("Информатика", date(2022, 6, 20), "Кузнецов К.К.", 5),
    ]),
    Student("Петров", "Петр", date(2001, 2, 20), [
        Exam("Математика", date(2022, 6, 10), "Петров П.П.", 4),
        Exam("Физика", date(2022, 6, 15), "Сидоров С.С.", 4),
        Exam("Информатика", date(2022, 6, 20), "Кузнецов К.К.", 3),
    ]),
    Student("Сидоров", "Семен", date(2002, 3, 25), [
        Exam("Математика", date(2022, 6, 10), "Петров П.П.", 5),
        Exam("Физика", date(2022, 6, 15), "Сидоров С.С.", 5),
        Exam("Информатика", date(2022, 6, 20), "Кузнецов К.К.", 5),
        Exam("Химия", date(2022, 6, 25), "Иванов И.И.", 4),
    ]),
    Student("Кузнецов", "Кирилл", date(2000, 4, 30), [
        Exam("Математика", date(2022, 6, 10), "Петров П.П.", 3),
        Exam("Физика", date(2022, 6, 15), "Сидоров С.С.", 3),
        Exam("Информатика", date(2022, 6, 20), "Кузнецов К.К.", 4),
    ]),
    Student("Алексеев", "Алексей", date(2001, 5, 5), [
        Exam("Математика", date(2022, 6, 10), "Петров П.П.", 4),
        Exam("Физика", date(2022, 6, 15), "Сидоров С.С.", 5),
        Exam("Информатика", date(2022, 6, 20), "Кузнецов К.К.", 5),
        Exam("Химия", date(2022, 6, 25), "Иванов И.И.", 5),
    ]),
]

# Найдем студента с самой лучшей успеваемостью
best_average_grade = 0
best_student = None

for student in students:
    average_grade = student.average_grade()
    if average_grade > best_average_grade:
        best_average_grade = average_grade
        best_student = student

# Выводим ФИО, предметы и оценки студента с самой лучшей успеваемостью
print(f"Студент с самой лучшей успеваемостью: {best_student.last_name} {best_student.first_name}")
print("Оценки:")
for exam in best_student.exams:
    print(f"Предмет: {exam.subject}, Оценка: {exam.grade}, Преподаватель: {exam.teacher}, Дата экзамена: {exam.exam_date}")